# Generated by Django 4.0.5 on 2022-06-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200)),
                ('itemName', models.CharField(max_length=300)),
                ('perItemPrice', models.CharField(max_length=100)),
                ('totalQuantity', models.CharField(max_length=100)),
                ('totalPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
